frequency: 'daily'
cumulated_csv_path: ''
group_identifiers: ['category']
smoothing_window_size: 0
timeseries_min_length: 50
min_prediction_length: 14
max_prediction_length: 60
min_encoder_length: 60
max_encoder_length: 365
target_variable: 'cantitate'
static_categoricals: []
static_reals: []
time_varying_known_categoricals: []
time_varying_known_reals: ['pret']
time_varying_unknown_categoricals: ['um']
time_varying_unknown_reals: []
device: 'gpu'
batch_size: 96
max_epochs: 60
gradient_clip: 0.1
learning_rate: 0.00005
hidden_size: 64
lstm_layers: 1
attention_head_size: 16
hidden_continuous_size: 16
dropout: 0.1
reduce_on_plateau_patience: 3
early_stopping_patience: 15
loss_fn: 'RMSE'
best_model_out_path: 'best_model.txt'
start_date: '2022-01-01'
end_date: '2023-01-01'
