frequency: 'daily'
cumulated_csv_path: ''
smoothing_window_size: 0
max_prediction_length: 21
max_encoder_length: 120
target_variable: 'valoare'
group_identifiers: ['category']
static_categoricals: ['category']
static_reals: []
time_varying_known_categoricals: []
time_varying_known_reals: ['pret']
time_varying_unknown_categoricals: []
time_varying_unknown_reals: []
batch_size: 96
max_epochs: 60
gradient_clip: 0.1
learning_rate: 0.0002
hidden_size: 16
attention_head_size: 4
hidden_continuous_size: 8
dropout: 0.1
reduce_on_plateau_patience: 4
early_stopping_patience: 20
loss_fn: 'QuantileLoss'
best_model_out_path: 'best_model.txt'
