frequency: 'daily'
cumulated_csv_path: ''
max_prediction_length: 10
max_encoder_length: 50
target_variable: 'valoare'
group_identifiers: ['category']
static_categoricals: ['category']
static_reals: []
time_varying_known_categoricals: []
time_varying_known_reals: ['pret']
time_varying_unknown_categoricals: []
time_varying_unknown_reals: []
batch_size: 64
max_epochs: 50
gradient_clip: 0.1
learning_rate: 0.0001
hidden_size: 16
attention_head_size: 4
hidden_continuous_size: 8
reduce_on_plateau_patience: 5
loss_fn: 'QuantileLoss'
best_model_out_path: 'best_model.txt'
