frequency: 'daily'
cumulated_csv_path: ''
group_identifiers: ['tmp']
smoothing_window_size: 0
timeseries_min_length: 200
min_prediction_length: 30
max_prediction_length: 30
min_encoder_length: 200
max_encoder_length: 300
target_variable: 'valoare'
static_categoricals: ['tmp']
static_reals: []
time_varying_known_categoricals: []
time_varying_known_reals: ['pret', 'month']
time_varying_unknown_categoricals: []
time_varying_unknown_reals: []
device: 'gpu'
batch_size: 96
max_epochs: 60
gradient_clip: 0.05
learning_rate: 0.00005
hidden_size: 256
lstm_layers: 2
attention_head_size: 4
hidden_continuous_size: 16
dropout: 0.1
reduce_on_plateau_patience: 5
early_stopping_patience: 15
loss_fn: 'QuantileLoss'
best_model_out_path: 'best_model.txt'
start_date: '2022-01-01'
end_date: '2023-01-01'
