combined_csv_path: D:\Master\disszertacio\time-series-forecast\data\combined.csv
frequency: 'daily'
group_identifiers: []
smoothing_window_size: 0
daily_seasonality: False
weekly_seasonality: True
yearly_seasonality: True
interval_width: 0.95
future_dataframe_periods: 100
timeseries_min_length: 30
start_date: '2022-01-01'
end_date: '2023-01-01'
