combined_csv_path: C:\Users\bas6clj\time-series-forecast\data\combined.csv
frequency: 'weekly'
group_identifiers: []
smoothing_window_size: 0
daily_seasonality: False
weekly_seasonality: True
yearly_seasonality: True
interval_width: 0.95
future_dataframe_periods: 100
timeseries_min_length: 30
start_date: '2022-01-01'
end_date: '2023-01-01'
