frequency: 'daily'
group_identifiers: ['category']
smoothing_window_size: 0
daily_seasonality: False
weekly_seasonality: True
yearly_seasonality: True
interval_width: 0.9
future_dataframe_periods: 100
timeseries_min_length: 50
start_date: '2022-01-01'
end_date: '2023-01-01'
